.github/workflows/deploy.yml

AWS 배포 자동화를 위한 GitHub Actions 워크플로우 설정 추가
Related to: TICO-139

[SETTING] CI/CD 워크플로우 설정 (TICO-53)

---

backend/pomoro-do/Dockerfile

Github Action을 이용한 CI/CD 파이프라인을 설정하기 위해 backend 프로젝트에 도커파일을 추가
Related to: TICO-139

[BUILD] CI/CD 설정을 위한 도커파일 추가 (TICO-60)

---

.github/workflows/deploy.yml

AWS 배포 자동화를 위한 GitHub Actions 워크플로우 문제 해결
- 프로젝트 경로 수정
- SSH 연결 실패 -> Github Secrets SSH KEY 추가하여 비밀번호 대신 SSH 키 인증을 사용
- docker run 명령어가 여러 줄에 걸쳐있어 에러 발생 -> docker run 명령을 한 줄로 작성
Related to: TICO-139

[FIX] CI/CD 워크플로우 문제 해결 (TICO-140)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/CustomTimeText.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/Extensions.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/Color.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/view/EditTimerDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/view/PomodoroTimer.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/view/TimerRootScreen.kt

1. 타이머 메인 화면의 다크모드에 따른 색상을 변경함.
2. 타이머 변경 dialog를 열 때 클릭하는 CustomTimeText의 click animation을 없앰.

[FEAT] 타이머 메인 화면(다크모드)(TICO-40)

---

.github/workflows/nginx-deploy.yml
.github/workflows/pomorodo-deploy.yml

1. Nginx 배포 워크플로우 작성
2. Nginx 배포 워크플로우 문제 해결
- Docker Hub 푸시 권한 문제 해결: 이미지 이름에 사용자 이름 포함
- Docker 컨테이너 실행 스크립트 수정: 백슬래시 뒤 공백 제거
- Docker 이미지 이름에 사용자 이름과 회사명 포함
- Docker 컨테이너 실행 스크립트 수정: 백슬래시 뒤 주석 제거
3. pomorodo 워크플로우 업데이트
- 파일명 'deploy'에서 'pomorodo-deploy'로 변경
- Docker 이미지 및 컨테이너 이름에 환경변수 적용
- SSH 액션 버전 업그레이드
- Docker 실행 명령어 가독성 향상을 위한 줄바꿈
Ref: TICO-58, TICO-152

[FEAT] Nginx 배포 워크플로우 작성 및 문제 해결 (TICO-148)

---

nginx/conf/conf.d/default.conf

Nginx 설정에 HTTPS 리다이렉션 추가
Ref: TICO-147, TICO-147

[FEAT] Nginx 설정 추가

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/CheckGroupMemberBottomSheet.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/OpenSettingsBottomSheet.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/darkiconpack/IcMuteDark.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/darkiconpack/IcSoundDark.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/darkiconpack/IcVibrateDark.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/lighticonpack/IcMuteLight.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/lighticonpack/IcSoundLight.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/lighticonpack/IcVibrateLight.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/AlarmOptions.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/MyPageScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/TimerSettingScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/IconPackString.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/__DarkIconPack.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/__LightIconPack.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/GroupBottomSheet.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- 타이머 종료 알림을 설정하는 bottom sheet을 구현함.
- 기존 bottom sheet의 drag handle design을 바꿈.
Resolves: TICO-66
Related to: TICO-61

[FEAT] 타이머 세팅 UI 구현(TICO-65)

---

nginx/conf/conf.d/default.conf

HTTPS 요청을 받을 때 올바르게 리다이렉트하도록 Nginx 설정을 수정
Ref: TICO-147

[FIX] Nginx HTTPS 리다이렉트 및 프록시 설정 추가 (TICO-147)

---

nginx/conf/conf.d/default.conf

HTTPS로 들어온 요청을 프록시 서버로 전달하는 설정 추가

[FIX] Nginx HTTPS  프록시 설정 추가 (TICO-147)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SwaggerConfig.java
backend/pomoro-do/src/main/resources/application.yml

FRAMEWORK로 변경하여, Nginx 리버스 프록시에서 전달되는 X-Forwarded 헤더를 올바르게 처리

[FIX] X-Forwarded 헤더 처리 개선 (TICO-215)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/AdminJoinDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/AdminLoginDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/entity/User.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/base/CustomSuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/controller/RootController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/CustomErrorCode.java
nginx/conf/conf.d/default.conf

- 백엔드 개발자를 위한 관리자 회원 가입 및 로그인 API를 구현하고 JWT를 발급
- NGINX 설정 업데이트: 프록시 재설정 및 SSL 강화
Ref: TICO-147, TICO-129

[FEAT] 관리자 회원 가입 및 로그인 API 구현 (TICO-222)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/entity/Refresh.java

새로운 필드 deviceId를 추가하고 빌더 메서드를 업데이트
Related to: TICO-206

[FEAT] 기기고유번호 컬럼을 Refresh 엔티티에 추가 (TICO-214)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/TokenDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java

- TokenDTO에 refreshToken 필드 추가
- 쿠키 저장 방식을 제거하고 TokenDTO에서 리프레시 토큰 직접 관리
Related to: TICO-162, TICO-206, TICO-240, TICO-241, TICO-244

[FEAT] TokenDTO 수정 및 리프레시 토큰 쿠키 저장 방식 제거 (TICO-242)

---

.github/workflows/pomorodo-deploy.yml
backend/pomoro-do/build.gradle
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/ImageDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/ImageService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/ImageServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/ErrorCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/S3Config.java
backend/pomoro-do/src/main/resources/application.yml

- Spring Cloud AWS Starter 의존성 추가로 AWS S3와 연동
- application.yml에 AWS S3 설정 추가 및 필요한 시크릿 환경 변수 적용
- S3 접근을 위한 S3Config 클래스 추가
- S3에 이미지 업로드 기능 구현
- 이미지 업로드 API 추가
- GitHub Actions에 S3 관련 환경 변수 추가하여 CI/CD 파이프라인 개선
Resolves: TICO-257, TICO-235, TICO-256
Related to: TICO-238, TICO-264

[FEAT] AWS S3 스토리지 통합을 통한 이미지 업로드 기능 추가 (TICO-239)

---

.github/workflows/pomorodo-deploy.yml

GitHub Actions에서 환경 변수를 적용하여 설정을 외부에서 관리하도록 변경
Related to: TICO-264

[FEAT] GitHub Actions에 환경 변수 적용 (TICO-247)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/UserController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/UserDetailDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/UserRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java

- 현재 로그인한 사용자의 상세 정보를 가져오는 기능 구현
- 다른 사용자의 상세 정보를 가져오는 기능 구현
Related to: TICO-162

[FEAT] 사용자 정보 조회 API 추가 (TICO-251)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/UserController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/controller/RootController.java

사용자 및 이미지 관련 API에 대한 Swagger 문서화 추가
Related to: TICO-162, TICO-251, TICO-209, TICO-235

[FEAT] Swagger 문서화 추가 (TICO-225)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/entity/Follow.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/FollowRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/ErrorCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/util/ValidationUtils.java

현재 인증된 사용자가 특정 사용자를 팔로우하는 기능을 추가
Related to: TICO-248

[FEAT] 팔로우 API 구현 (TICO-266)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/FollowUserDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/FollowRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java

현재 인증된 사용자가 팔로우 중인 사용자 목록을 조회하는 기능을 추가
Related to: TICO-248, TICO-255, TICO-209

[FEAT] 팔로우 목록 조회 API 구현 (TICO-249)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java

API 디자인의 일관성을 개선하기 위해 현재 인증된 사용자의 팔로우 목록 조회 엔드포인트를 변경
Related to: TICO-248

[REFACTOR] 현재 사용자의 팔로우 목록 조회 엔드포인트 변경 (TICO-249)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/UserDetailDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/FollowRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/controller/RootController.java

- 사용자가 팔로우하는 사람 수와 사용자를 팔로우하는 사람 수를 계산하는 로직 추가
- Swagger 문서 태그 통일: 백엔드 관련 컨트롤러에 "BackEnd: 백엔드" 태그 적용
Related to: TICO-225, TICO-209, TICO-162

[FEAT] 팔로우 수 계산 로직 추가 및 Swagger 태그 통일 (TICO-251)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/common/constants/CategoryConstants.java

- 구글 회원가입 시 기본 카테고리 자동 생성 기능 추가
- 카테고리 생성 시 상수 클래스를 사용하여 기본 값 관리
Related to: TICO-162, TICO-255

[FEAT] 기본 카테고리 생성 로직 추가 (TICO-267)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/request/CategoryDetailDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/CategoryDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GeneralCategoryDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GroupCategoryDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/Category.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/GroupMember.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/GroupMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java

사용자가 속한 그룹과 일반 카테고리를 조회하는 기능을 추가

[FEAT] 일반 및 그룹 카테고리 조회 로직 추가 (TICO-253)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GroupInviteDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/GroupMember.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/GroupMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/enums/GroupInvitationStatus.java

현재 인증된 사용자가 초대된 그룹 카테고리를 조회하는 기능을 추가

[FEAT] 초대 상태에 따른 그룹 카테고리 조회 로직 추가 (TICO-269)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GroupInviteDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java

GroupInviteDTO 응답에서 타입 정의 오류 수정

[FIX] GroupInviteDTO 응답에서 타입 정의 오류 수정 (TICO-269)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GroupInviteDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java

- API 엔드포인트를 "/group/invitations"로 변경
- Swagger 문서화: 빈 배열 반환 설명 추가

[FIX] 초대된 그룹 카테고리 조회 API 수정 (TICO-269)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/CategoryDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GeneralCategoryDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GroupCategoryDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/InvitedGroupDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/Category.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/GroupMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java

- 일반, 그룹, 초대받은 그룹 및 통합 조회 기능 구현
- 일반/그룹 가나다 순 정렬
- 초대받은 그룹 초대 날짜 내림차순 정렬
Resolves: TICO-287, TICO-288

[FEAT] 카테고리 조회 기능 추가 (TICO-276)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/request/CategoryCreationDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/CategoryDetailDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/GroupMemberDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/GroupMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java

카테고리 ID를 기반으로 상세 정보를 조회하는 API 구현

[FEAT] 카테고리 상세 정보 조회 기능 추가 (TICO-274)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/UserController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SwaggerConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/controller/RootController.java

- API 버전별 엔드포인트 생성
- 각 버전에 대한 Swagger 그룹화 설정 추가

[FEAT] API 버저닝 추가 (TICO-282)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/service/AuthApiService.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/service/ReissueTokenService.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/service/TokenApiService.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/CategoryRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt

- API 주소 변경
- 시작 화면 splash로 변경
Fixes: TICO-307

[CHORE] API 주소변경 (TICO-307)

---

Mobile/PomoroDo/app/build.gradle
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/service/AuthApiService.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/service/ReissueTokenService.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/service/TokenApiService.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/CategoryRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/MyPageScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/viewmodel/MyPageViewModel.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- 온라인 모드로 전환 메뉴 추가
- local.properties에 버전정보 추가
- 친구 초대 메뉴 삭제
- 타이머 종료 후 스톱워치로 전환 메뉴를 버전에 따라 보이도록 설정
-  버전 정보는 local.properties에 위치.

[FEAT] 마이페이지 변경(TICO-318)

---

Mobile/PomoroDo/app/build.gradle
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/MyPageScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/viewmodel/MyPageViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/setting/view/SettingScreen.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- v1에 따라 menuList를 분리함.
Fixes: TICO-320
Related to: TICO-311

[FEAT] 환경설정 화면 버전에 맞게 수정(TICO-320)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/request/CategoryCreationDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/Category.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/statistics/entity/TimeStats.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/timer/entity/Timer.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/timer/entity/TimerTodo.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/todo/entity/Todo.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/todo/entity/TodoLike.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/entity/Follow.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/util/DateUtils.java

- 기능 명세서 변경에 따른 데이터베이스 수정
- DB 변경에 따른 카테고리 생성, 조회 서비스 로직 수정
- 날짜별 관리를 위한 date 관련 로직 추가
Resolves: TICO-321, TICO-323
Related to: TICO-305, TICO-255

[FEAT] 기능 명세서 변경에 따른 DB 및 서비스 로직 변경 (TICO-299)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/GroupMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/util/DateUtils.java

- 날짜 기반 필터링으로 불필요한 데이터 조회 방지
- 멤버 수 계산 로직 최적화

[REFACTOR] 카테고리 조회 로직 날짜 필터링 및 성능 개선 (TICO-286)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/response/CategoryDetailDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java

조회한 유저가 그룹장인지 확인하는 hostStatus 필드를 DTO에 추가

[FEAT] 카테고리 상세 응답에 hostStatus 필드 추가 (TICO-331)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/FollowRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/ErrorCode.java

언팔로우 요청 처리 및 팔로우 관계 예외 처리 추가
Related to: TICO-248

[FEAT] 언팔로우 기능 구현 (TICO-322)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/dao/CalendarDao.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/PomorodoDatabase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/calendar/CalendarLocalDataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/calendar/CalendarLocalDataSourceImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/entity/CalendarDateEntity.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/CalendarDate.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/CalendarRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/DataSourceModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/DatabaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/RepositoryModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/UseCaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/repository/CalendarRepository.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/calendar/GetCalendarDateForMonthUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/calendar/InsertCalendarDateForMonthUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/calendar/UpdateCalendarDateForMonthUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/viewmodel/TodoViewModel.kt

**추가 사항**
- 달력 기능 연결
- 날짜 별 투두 조회, 생성, 삭제, 수정 기능 추가
- 임시 초기 투두, 달력 데이터 추가
Resolves: TICO-179
Related to: TICO-173

[FEAT] 달력 room 기능 추가 (TICO-179)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/auth/dto/GoogleUserInfo.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/auth/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/auth/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/auth/service/CustomUserDetailsService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/UserController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/AdminRequest.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/ImageResponse.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/UserDetailResponse.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/entity/User.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/UserRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserServiceImpl.java

- User 엔티티 필드명 username → email 변경
Related to: TICO-378

[REFACTOR] User 도메인 개편 및 필드명 수정 (TICO-372)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/common/util/NetworkConstants.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/Base.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/remote/models/response/BaseResponse.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/viewModel/AuthViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/splash/viewModel/SplashViewModel.kt

**변경사항**
- 불필요한 프로퍼티인 status 제거
- 관련 코드도 정리
Fixes: TICO-379

[CHORE] api 응답 base class 프로퍼티 변경(TICO-379) 

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryInvitationRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryInvitationServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java

- 단건 및 일괄 초대 로직에 중복 초대 방지 조건 추가
- 내부 메서드 hasPendingInvitation 구현

[FEAT] PENDING 상태 초대장 중복 생성 방지 (TICO-398)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/common/util/Converters.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/dao/TimerDao.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/PomorodoDatabase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/timer/TimerLocalDataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/timer/TimerLocalDataSourceImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/entity/TimerSettingEntity.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/TimerSettingData.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/TimerRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/DataSourceModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/DatabaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/RepositoryModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/UseCaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/repository/TimerRepository.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/timer/GetConcentrationGoalUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/timer/InsertConcentrationGoalUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/timer/UpdateConcentrationGoalUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/timer/UpdateTargetTimeUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/view/TimerRootScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/viewmodel/TimerSetupViewModel.kt

- 목표 집중 시간 초기 데이터 삽입 기능 구현
- 추후 기능 삭제 예정
- 목표 집중 시간을 불러오는 기능 구현
- 목표 집중 시간을 변경하는 기능 구현
- 데이터베이스 버전을 변경할 때 자동으로 기존의 데이터를 삭제하는 기능 추가
Solved: TICO-356
Related to: TICO-173

[FEAT] 목표 집중 시간 기능 구현(TICO-356)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/MainActivity.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/MainViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/common/util/Converters.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/NetworkModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppMainNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/network/NetworkMonitor.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/network/NetworkMonitorImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/AppState.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/BottomBar.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/HomeScreen.kt

- 불필요한 파일 제거(TempComposable)
- Converter의 userList를 Json으로 변환하는 함수의 null 처리
- BottomBar의 preview 제거 및 변경을 권고하는 방향으로 코드 수정
- 코드 분리 및 정리
- AppMainNavHost로 코드 분리
- AppState에서 navController를 관리하도록 변경하고 mainNavController와 homeNavController로 변수 구분
- 실시간으로 Network 상태를 수집하는 로직 구현
- MainViewModel 구현
- 네트워크 상태를 구독해서 받는 변수
- appState에서 네트워크 상태를 받는 변수와 오프라인 유무의 변수 구현
Resolves: TICO-185
Ref: TICO-221
Related to: TICO-174

[FEAT] 오프라인 구조 구현(TICO-185) 

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryMemberController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/dto/request/CategoryLeaveRequest.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/Category.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/entity/CategoryMember.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/enums/CategoryDeletionOption.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryMemberService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryMemberServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/validator/CategoryValidator.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/ErrorCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/response/SuccessCode.java

- 일반 멤버는 삭제 정책에 따라 탈퇴
- 그룹장은 위임 후 탈퇴 또는 예외 처리
- 탈퇴 시 역할, 할일 상태 등 갱신

[FEAT] 그룹 카테고리 나가기 API 구현 (TICO-400)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/follow/view/AddFollowerScreen.kt

변경 사항
- 크기 수정과 간격 조절
Fixes: TICO-418

[CHORE] 팔로우 추가 화면의 검색 버튼 크기 오류 수정(TICO-418) 

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/view/LogInScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/AppState.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

변경 사항
- 스낵바에 표시되는 string 리소스 추가
- appState에 snackBarHostState 추가
- 오프라인 로그인 클릭 시, 실행 함수 추가
- 네트워크 스낵바 표시
- 네트워크 연결 상태이며, 오프라인 모드라면 스낵바를 표시
Related to: TICO-174
Resolves: TICO-415

[FEAT] 네트워크 스넥바 ui(TICO-415)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/Profile.kt

[FEAT] 프로필 이미지 캐싱 옵션 추가 (TICO-457)
