Tico-Corp/Pomoro-Do

Mobile/PomoroDo/app/build.gradle
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/view/SignUpScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/IcProfileDefault.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml
Mobile/PomoroDo/gradle/libs.versions.toml

회원가입 화면을 구현함.
- 프로필 변경 아이콘
- 구글 프로필을 받아오지 않을 경우 기본 프로필을 나타냄
- 구글 프로필 링크를 jetpack glide를 통해 나타냄
- 닉네임 입력 텍스트 박스
- BasicTextField를 이용하여 구현
- focused 상태일 때 label과 indicator가 primary-container 컬러로 변함.
- 가입 버튼
- 닉네임 입력 시 가입 버튼 활성화.
Resolves: TICO-32
Related to: TICO-20

[FEAT] 회원가입 화면 구현 (TICO-32)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/TodoData.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/NavControllerExtensions.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/GroupDeleteDialogs.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/InfoCategoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/Constants.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/SimpleAlertDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/TodoItem.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/TodoListDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/history/view/HistoryDeleteDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/history/view/HistoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/HomeScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/running/view/ConcentrationTimerSceen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/running/viewmodel/TimerRunningViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/view/CustomCircularTimer.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/view/EditTimerDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/view/PomodoroTimer.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/view/TimerRootScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/viewmodel/TimerSetupViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/viewmodel/TimerViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/TodoListScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/viewmodel/TodoViewModel.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- 동일한 navController 간에 인자를 전달하고 받는 확장함수 생성 : ```NavControllerExtensions.kt```
- TodoListDialog 생성
- dialog의 외부를 클릭하거나 뒤로가기 버튼을 클릭하면 상태 변경을 초기화하고 타이머를 재개함.
- 초기화 버튼을 클릭하면 상태 변화가 초기화 됨.
- 집중 시작 화면 연결
- 집중 시작 버튼 클릭 시 mainNavController의 savedStateHolder에 타이머 정보 저장
- TodoItem Composable 함수 위치 변경
- todo 패키지의 TodoItem과 TodoCheckBox의 위치를 common 패키지로 변경함.
- TodoData 인자 변경
- 연결된 category의 Id 인자를 추가함.
- SimpleAlertDialog 함수 인자 변경
- onDismissRequest를 파라미터를 받지 않는 함수로 변경함.
- ConcentrationTimerScreen 함수 내용 분리
- 함수의 화면을 별도의 composable 함수로 분리 : ```TimerScreenLayout```, ```updateTimer```
Fixes: TICO-54
Related to: TICO-33

[FEAT] 집중 종료 후 화면 구현(TICO-54)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/running/view/BreakTimerScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/running/view/ConcentrationTimerSceen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/running/viewmodel/TimerRunningViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/view/TimerRootScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/timer/setup/viewmodel/TimerSetupViewModel.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- 휴식 시간 화면 구현
- 휴식 시간 화면 연결
- 휴식 시간 종료 시 홈 화면으로 이동하도록 구현
- 집중, 휴식 타이머 초기화
- 다크모드로 전환할때 타이머가 초기화 되는 문제 해결
- 집중 화면과 휴식 화면이 공통으로 사용하는 내 상수 변경
- home 화면의 총 집중 시간, 총 휴식 시간 상수를 변수로 변경
로컬 DB와 연결하면 휴식시간 타이머가 종료되고 데이터를 DB에 작성, Home에서 이를 불러오도록 변경.
Fixes: TICO-59
Related to: TICO-33

[FEAT] 휴식 모드 UI 구현(TICO-59)

---

Mobile/PomoroDo/app/build.gradle
Mobile/PomoroDo/app/proguard-rules.pro
Mobile/PomoroDo/app/src/main/AndroidManifest.xml
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/PreferencesManager.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/AuthRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/RepositoryModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/UseCaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/repository/AuthRepository.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/ClearTokenUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/GetTokenUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/SaveTokenUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/view/LogInScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/view/PhotoChooseDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/view/SignUpScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/auth/viewModel/AuthViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/AddCategoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/GroupDeleteDialogs.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/GroupMemberChooseScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/InfoCategoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/CustomButton.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/CustomTextField.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/Extensions.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/Color.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/TodoListScreen.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml
Mobile/PomoroDo/app/src/main/res/xml/path_provider.xml
Mobile/PomoroDo/gradle/libs.versions.toml

**변경 사항**
- CustomTextButton에 border의 두께 변수 추가
- customTextField 다크모드 적용 안되는 문제 해결
- 텍스트 컬러와 스타일, 커서 색상 적용
- 라이브러리 버전 변경
- kotlin 버전에 맞는 hilt 버전으로 변경
- 2.44 -> 2.46
- 불필요한 로그 제거 및 변경
---
**새로운 사항**
- 라이브러리 추가
- google login을 위한 credential manager jetpack 라이브러리 추가
- 1.3.0-beta04
- 암호화된 sharedpreference를 사용하기 위한 라이브러리 추가
- interceptor 추가를 위한 라이브러리 추가
- 리소스 추가
- string
- 다크모드 로그인을 위한 색상 추가
- 이미지 파일 생성하는 함수와 토스트 메시지를 띄우는 확장함수 추가
- 카메라 권한과 provider 설정
- 로그인 화면
- 다크 모드와 오프라인 버튼 추가
- 구글 로그인 기능 추가
- 로그인과 회원가입에 필요한 authViewModel
- 사진 선택 Dialog 추가
- 사진 촬영
- 앨범에서 선택
- 기존 이미지 적용(이미지가 있을때만 표시)
- 회원가입 화면
- 카메라 권한 확인 코드 추가
- dialog 추가로 컴포저블 분리
- 사진 선택 도구 실행 기능 추가
- camera 앱 활용 기능 추가
- sharedPreferences 추가
- google idToken을 viewmodel에 저장
- authToken을 sharedPreference에 저장
Fixes: TICO-133

[FEAT] 구글 로그인 연결 (TICO-133)

---

nginx/conf/conf.d/default.conf

/api/ 경로로 들어오는 요청이 프록시를 거쳐 백엔드 서버로 전달될 때, 요청 경로의 prefix를 명시적으로 전달

[FIX] /api 경로에 X-Forwarded-Prefix 헤더 추가 (TICO-215)

---

backend/pomoro-do/build.gradle
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/base/AppInfoDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/controller/RootController.java
backend/pomoro-do/src/main/resources/application.yml
nginx/conf/conf.d/default.conf

- HTTPS와 HTTP 간의 프록시 설정 문제를 해결하기 위해 "/api" 접두사를 추가하여 REST API 엔드포인트 구현
- 기본 정보 API를 추가하여 애플리케이션 이름, 버전, 환영 메시지 등을 포함한 정보 반환
- Nginx의 프록시 설정을 수정하여 "/api" 접두사 추가
Related to: TICO-209, TICO-161, TICO-216

[FIX] "/api" 접두사를 사용한 REST API 엔드포인트 구현 (TICO-215)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/controller/RootController.java
nginx/conf/conf.d/default.conf

Nginx 설정을 수정하여 HTTPS로 연결된 서버에서 포트 8080에 위치한 백엔드 서버로 요청을 프록시하도록 변경
Related to: TICO-209, TICO-161

[FIX] Nginx 프록시 서버 설정 변경 (TICO-215)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTFilter.java
nginx/conf/conf.d/default.conf

- "/api" 경로의 프록시 설정 수정
- JWTFilter 내부의 조건문을 수정하여 JWT 필터를 우회할 수 있도록 수정
Related to: TICO-209, TICO-164

[FIX] Nginx 프록시 수정 및 JWTFilter 수정 (TICO-215)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SwaggerConfig.java

- Swagger 테스트 시 발생한 CORS 문제 해결을 위한 설정 추가
- HTTPS 및 HTTP 엔드포인트를 포함한 서버 URL 업데이트
- 서비스 제목, 설명, 버전 및 연락처 정보 상세히 업데이트

[FIX] Swagger 테스트 시 CORS 문제 해결 및 서버 설정 수정 (TICO-215)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/model/Follow.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/NavigationDestination.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/HomeScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/FollowListScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/MyPageScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/viewmodel/FollowViewModel.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- 뒤로가기 버튼과 제목만 있는 상단바 구현
- 팔로우 메뉴 탭 구현
- 팔로우 목록을 좌우로 드래그하여 각 메뉴끼리 화면을 전환할 수 있도록 구현
- 팔로우 데이터 모델 생성
- followId: 팔로우 id
- profileUrl: 프로필 url
- name: 사용자 이름
- isFollowing: 팔로우 여부(변경 가능 변수)
- 임시 데이터 생성(followList)
Resolves: TICO-68
Related to: TICO-61

[FEAT] 팔로우 목록 UI 구현(TICO-68)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/Category.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/AddCategoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/CategoryOutDialog.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/CategoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/GroupMemberChooseScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/InfoCategoryScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/viewModel/AddCategoryViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/viewModel/CategoryViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/viewModel/InfoCategoryViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/Extensions.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/TodoListScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/TodoScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/viewmodel/TodoViewModel.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

**변경 사항**
- UI 보충 작업
- cateogry 정보 확인에서 categoryId를 navigation argument로 전달하고, savedStateHandle로 저장 및 가져 옴
- 그룹원 선택 화면을 info 화면과 add 화면에 따라 다른 viewModel을 적용
- 투두에서 데이터 연결하지 않은 부분 보충
- 그룹 나가기 다이얼로그를 공용으로 사용할 수 있게 변경
- Category 데이터 변수 추가 및 임시 데이터 변경
- CategoryViewModel을 각 화면에 따라 분리
- AddCategoryViewModel
- InfoCategoryViewModel
- 카테고리 관리 화면에서 카테고리를 클릭시 정보로 들어가지 않는 문제 해결
-  이중 클릭 함수로 카테고리 태그에 클릭 함수가 적용되지않아서 오버라이딩으로 새로운 카테고리 태그 컴포저블 생성
- 카테고리 추가 화면 보충
- 공개설정의 그룹 설명을 그룹 카테고리일 때만 보이게 설정
- 유형에서 글자를 눌러도 라디오 버튼이 변경되게 변경
---
**추가 사항**
- loading을 위한 skeleton extensions 추가
- string 리소스 추가
Fixes: TICO-204

[FEAT] UI 보충 (TICO-204)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/GoogleJoinDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/base/ErrorResponseDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/base/SuccessResponseDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/common/enums/TokenType.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SwaggerConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/CustomErrorCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/ErrorResponseEntity.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/GlobalExceptionHandler.java

- 구글 idToken 요청 헤더 이름 변경으로 Swagger에서 JWT 토큰 헤더와의 충돌 해결
- 로그인 및 회원 가입 로직의 에러 처리 강화
- CustomException 외 다양한 예외 처리 로직 추가
- 표준화된 오류 응답 구현
- 성공 및 실패 시 응답 형태 변경
Related to: TICO-162, TICO-209, TICO-198

[FEAT] 구글 idToken 요청 로직 변경 및 에러 응답 표준화 (TICO-229)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/TokenDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/entity/Refresh.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/RefreshRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/LoginFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/ErrorCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SecurityConfig.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/response/SuccessResponseDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/util/CookieUtil.java

- JWT 만료 시간을 yml 설정 파일로 관리하여 유지보수성 향상
- 리프레시 토큰을 사용한 액세스 토큰 재발급 API 구현
- 토큰 검증 로직 추가 (존재 여부, 만료 여부, 유효성 확인)
- 액세스 토큰 재발급 시 리프레시 토큰을 갱신하여 보안성 강화
- 리프레시 토큰을 응답 쿠키에 추가하여 클라이언트의 편의성 향상
- 서버측에서 리프레시 토큰 관리용 Entity 생성
- 리프레시 토큰 발행 시 서버에 저장
- 액세스 토큰 재발급 시 리프레시 토큰 대조 후 기존 삭제 및 새 발급
- 로그아웃 시 리프레시 토큰 쿠키 만료 및 서버에서 삭제 기능 추가
- 토큰 검증 로직 분리하여 유지보수성 개선
Resolves: TICO-207, TICO-182,  TICO-180, TICO-226
Related to: TICO-162, TICO-206, TICO-164, TICO-208

[FEAT] 토큰 재발급 기능 구현 (TICO-224)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java

- 액세스 토큰만 반환하도록 JWT 반환 방식 변경
- Refresh 토큰을 데이터베이스에 저장하고 쿠키로 응답에 추가
Ref: TICO-180
Related to: TICO-206, TICO-164, TICO-162

[FEAT] 로그인 및 회원가입 JWT 반환 로직 수정 (TICO-227)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/RefreshRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/LoginFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/ErrorCode.java

- 토큰 검증 함수 에러 처리 세분화 및 로그 개선
- 기기의 고유번호를 헤더로 받아 DB 확인 작업을 통해 리프레시 토큰 검증
- 리프레시 토큰을 기준으로  리프레시 Entity를 조회하도록 로직 변경
Related to: TICO-206

[FEAT] 토큰 재발행 API 로직 변경 (TICO-241)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenServiceImpl.java

- Refresh 엔티티에 기기 고유번호 추가: 일관된 고유 식별자(UUID)를 사용하여 관리
- 새로운 토큰 저장 전에 기존 Refresh 토큰을 사용자명으로 삭제하는 로직 추가: 기존 토큰 무효화로 보안 강화
Related to: TICO-162

[FEAT] 관리자 회원가입 및 로그인 API 로직 변경 (TICO-244)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/ImageServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTUtil.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/LoginFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/util/CookieUtil.java

- 클라이언트에서 디바이스 정보를 전달하기 위해 Device-ID 헤더 추가
- 리프레시 토큰 검증 강화를 위해 기기 고유번호를 리프레시 토큰과 함께 DB에 저장
- 액세스 및 리프레시 토큰 문자열을 이넘으로 관리하여 가독성 향상
- 불필요한 로그 메시지 및 Swagger 로직 삭제, 주석 수정
Related to: TICO-162, TICO-164, TICO-206

[FEAT] 로그인 API에 디바이스 정보 추가 (TICO-240)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/response/ImageDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/ImageService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/ImageServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTFilter.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/enums/S3Folder.java

- 파일을 S3에 폴더별로 저장하도록 변경하여 저장 방식 개선
- 기기 고유번호 및 리프레시 토큰 저장 기능을 추가하여 사용자 식별 강화
- 프로필 이미지 등록 및 S3 업로드 기능을 추가하여 이미지 관리 개선
- 토큰 카테고리를 문자열 대신 이넘으로 관리하여 코드의 가독성 향상
Related to: TICO-237, TICO-206, TICO-162, TICO-164

[FEAT] 회원가입 API 개선 (TICO-236)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/UserController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/RefreshRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/UserRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AuthServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/TokenServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/UserServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/auth/jwt/JWTUtil.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/ErrorCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/util/ValidationUtils.java

- 유효성 검사 로직을 ValidationUtils 클래스로 분리
- 로그아웃 기능에 USERNAME 검증 로직 추가
- 현재 인증된 사용자의 계정을 삭제하는 기능을 추가
Related to: TICO-162, TICO-209, TICO-225

[FEAT] 회원 탈퇴 API 구현 (TICO-250)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/NavigationDestination.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/viewmodel/MyPageViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/setting/view/AppThemeScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/setting/view/SettingMenu.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/setting/view/SettingScreen.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

- 앱 테마 변경 화면 구현
- 앱 테마 변경 화면 연결
- 환경 설정 화면에서 화면 전환 시 현재 설정된 모드를 String으로 전송함.
Fixes: TICO-79
Related to: TICO-77

[FEAT] 앱 테마 변경 화면 구현 (TICO-79)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/AdminDTO.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/repository/FollowRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/FollowServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/code/SuccessCode.java

- 현재 사용자의 팔로워 목록 조회 기능을 추가
- 팔로우 및 팔로워 목록 조회 메서드 통합
Related to: TICO-248

[FEAT] 현재 사용자의 팔로워 목록 조회 API 구현 (TICO-279)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/NavigationDestination.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/CustomTopAppBar.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/follow/view/FollowScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/AppState.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/HomeScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/darkiconpack/IcBottomFollowDark.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/iconpack/lighticonpack/IcBottomFollowLight.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/member/view/MyPageScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/setting/view/SettingScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/IconPackString.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/__DarkIconPack.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/theme/__LightIconPack.kt
Mobile/PomoroDo/app/src/main/res/values/strings.xml

기존의 방식(마이페이지의 팔로워 정보에서 접근하던 방식)에서 새로운 방식(별도의 탭으로 구성)으로 변경
- 팔로워 탭 생성
- follow 패키지에 팔로워 화면 코드 이동
- CustomTopAppBarWithSingleButton를 CustomTopAppBarWithNavigation로 변경
- 마이페이지의 follow list 화면 연결 해제 및 코드 삭제

[FEAT] 팔로우 UI 수정 (TICO-316)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/config/SwaggerConfig.java

서버 이전으로 인해 swagger config의 URL 주소를 새로운 서버에 맞게 수정
Resolves: TICO-328

[SETTING] 서버 이전에 따른 swagger URL 주소 변경 (TICO-295)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/PomoroDoApplication.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/CategoryRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/repository/GroupMemberRepository.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/service/CategoryServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/scheduler/CategoryScheduler.java

매일 새벽 5시에 전날의 카테고리를 오늘 날짜로 자동 생성하는 스케줄러 추가
Related to: TICO-338

[FEAT] 카테고리 자동 생성 스케줄러 구현 (TICO-334)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/common/util/Converters.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/dao/CategoryDao.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/PomorodoDatabase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/category/CategoryLocalDataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/category/CategoryLocalDataSourceImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/entity/CategoryEntity.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/entity/UserEntity.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/Category.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/model/User.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/CategoryRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/DatabaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/UseCaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/repository/CategoryRepository.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/category/GetCategoryInfoUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/category/InsertCategoryUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/category/UpdateCategoryInfoUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/viewModel/CategoryAddViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/viewModel/CategoryInfoViewModel.kt

**추가 사항**
- 카테고리의 그룹원을 저장하기 위한 UserEntity 추가
- 카테고리 entity와 mapper 확장 함수 변경
- Converter 추가
- 그룹원을 저장하기 위한 user 목록을 json으로, json을 user 목록으로 전환하는 TypeConverter 추가
- user를 userEntity로 변환하는 mapper 확장함수 추가
- room DB에 초기 데이터 설정하는 로직 추가
- 카테고리 정보, 추가, 수정 UseCase 추가
- 카테고리 정보, 추가, 수정 UseCase 연결
**수정 사항**
- RoomDatabase 초기화 로직 리팩토링
- PomorodoDatabase에서 Singleton 관리 로직 제거
- @ Volatile 및 getDatabase 함수 삭제
- DATABASE_NAME을 companion object에서 상수로 변경
- DatabaseModule에서 RoomDatabase 빌더 직접 사용하도록 수정
- PomorodoDatabase.getDatabase 함수 호출 제거
- category를 Entity로 전환하는 확장 함수 수정
- category 로직 변경
- localDataSource, Repository, Dao의 매개변수 또는 이름 변경
Resolves: TICO-178
Related to: TICO-173

[CHORE] 카테고리 room 로직 변경 (TICO-178) 

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/auth/controller/AuthController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/category/controller/CategoryController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/FollowController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/ImageController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/UserController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/CustomException.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/ErrorResponseEntity.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/GlobalExceptionHandler.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/response/SuccessResponse.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/security/filter/JwtFilter.java

HTTP 상태 코드는 헤더에 포함되므로 에러 및 성공 응답 내부의 status 필드 제거
Related to: TICO-205

[REFACTOR] 응답 객체에서 중복된 status 필드 제거 (TICO-377)

---

backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/controller/AdminController.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/AdminLoginRequest.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/dto/request/AdminRegisterRequest.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/policy/InternalEmailPolicy.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminService.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/domain/user/service/AdminServiceImpl.java
backend/pomoro-do/src/main/java/com/tico/pomoro_do/global/exception/ErrorCode.java
backend/pomoro-do/src/main/resources/application.yml

- 관리자 이메일을 내부 전용 도메인으로 강제
- 검증 로직을 validateInternalOnly()로 통합
Related to: TICO-446

[REFACTOR] 관리자 도메인 정책 변경 및 검증 로직 개선 (TICO-428)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/AppState.kt

AppState.kt의 NavigationRoute 참조를 MainNavigationDestination으로 변경
Fixes: TICO-434
Related to: TICO-432

[ERROR] NavigationRoute가 전부 지워지지 않아 발생한 오류 해결(TICO-434)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/local/datasource/DataSource.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/data/repository/UserRepositoryImpl.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/di/UseCaseModule.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/model/Follow.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/repository/UserRepository.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/domain/usecase/user/GetMyUserIdUseCase.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavHost.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/AppNavigation.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/navigation/NavigationDestination.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/MainScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/CategoryInfoScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/CheckGroupMemberBottomSheet.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/viewModel/CategoryInfoViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/common/view/Profile.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/follow/view/AddFollowerScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/follow/view/FollowScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/follow/viewmodel/FollowViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/home/view/AppState.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/FollowTodoScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/GroupBottomSheet.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/TodoListScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/view/TodoScreen.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/viewmodel/FollowTodoViewModel.kt
Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/todo/viewmodel/TodoViewModel.kt

1. followViewModel을 member 패키지에서 follow 패키지로 이동
2. FriendTodoScreen을 FollowTodoScreen으로 이름 변경
3. Follow 모델의 followId의 데이터 타입을 Long에서 Int로 변경
4. 그룹원 프로필 또는 팔로우 프로필 클릭 시, 해당 유저의 팔로우 투두 리스트로 이동하는 로직 추가
(단, 해당 유저가 '나'일 경우 홈화면의 투두로 이동)

[FEAT] 팔로우 투두 리스트 이동 기능(TICO-431)

---

Mobile/PomoroDo/app/src/main/java/com/tico/pomorodo/ui/category/view/CategoryScreen.kt

오프라인 일 때, 그룹 카테고리 정보를 클릭하면 토스트 메시지로 지원하지 않는 기능이라고 안내

[CHORE] 그룹 카테고리 오프라인 추가 처리 (TICO-459)
